/**
 * Every action a hotkey can trigger. Ids are globally unique and so are the
 * key combinations bound to them: no action is ever chosen by "which part of
 * the screen is active", so a hotkey always does exactly one thing.
 */
export type HotkeyAction =
	// Canvas - blank and node context menus.
	| 'graph.addNode'
	| 'graph.createSubplan'
	| 'graph.inspectNode'
	| 'graph.openSubplan'
	| 'graph.convertToSubplan'
	| 'graph.toggleLock'
	| 'graph.toggleDone'
	| 'graph.deleteNode'
	| 'graph.splitByInputs'
	| 'graph.splitByOutputs'
	| 'graph.splitByBoth'
	| 'graph.shrinkToConnections'
	| 'graph.growToConnections'
	| 'graph.disableRecipe'
	| 'graph.disableMachine'
	| 'graph.disableFuel'
	| 'graph.disableGenerator'
	| 'graph.disableByproduct'
	| 'graph.removeProduct'
	| 'graph.disableResource'
	| 'graph.removeInput'
	// Planner - the canvas as a whole.
	| 'planner.calculate'
	| 'planner.rearrange'
	| 'planner.undo'
	| 'planner.redo'
	| 'planner.zoomIn'
	| 'planner.zoomOut'
	| 'planner.zoomFit'
	// Production request - one per tab of the panel, which is opened and
	// brought to the front first.
	| 'calculator.request'
	| 'calculator.resources'
	| 'calculator.recipes'
	| 'calculator.machines'
	| 'calculator.input'
	| 'calculator.byproducts'
	| 'calculator.power'
	| 'calculator.sink'
	| 'calculator.sloops'
	| 'calculator.overclocking'
	| 'calculator.optimisation'
	// Panels - each one opens, or comes to the front, or closes.
	| 'panel.plans'
	| 'panel.calculator'
	| 'panel.overview'
	| 'panel.inspector'
	| 'panel.power'
	| 'panel.items'
	| 'panel.buildCost'
	| 'panel.plannerSettings'
	| 'panel.codex'
	| 'panel.help'
	// Plans tree - these act on the open plan (or its folder).
	| 'plans.newPlan'
	| 'plans.newFolder'
	| 'plans.renamePlan'
	| 'plans.clonePlan'
	| 'plans.sharePlan'
	| 'plans.deletePlan'
	| 'plans.pickPlanIcon'
	| 'plans.resetPlanIcon'
	| 'plans.renameFolder'
	| 'plans.cloneFolder'
	| 'plans.shareFolder'
	| 'plans.deleteFolder'
	| 'plans.importOldTools'
	// Anywhere in the app.
	| 'app.search'
	| 'app.settings'
	| 'app.home'
	| 'app.back';
