/**
 * A closed union rather than string, so a button can never name an id the editor does not offer
 * and a renamed id breaks the build instead of silently hiding buttons.
 */
export type HelpTopicId =
	| 'planner.first-plan'
	| 'planner.graph'
	| 'planner.manual-editing'
	| 'planner.machine-groups'
	| 'planner.subplans'
	| 'planner.calculation'
	| 'planner.folders'
	| 'planner.sharing'
	| 'planner.save-import'
	| 'planner.old-tools'
	| 'planner.panels'
	| 'panel.plans'
	| 'panel.calculator'
	| 'panel.overview'
	| 'panel.inspector'
	| 'panel.power'
	| 'panel.items'
	| 'panel.build-cost'
	| 'panel.settings'
	| 'panel.codex'
	| 'panel.help'
	| 'request.production'
	| 'request.resources'
	| 'request.recipes'
	| 'request.machines'
	| 'request.input'
	| 'request.byproducts'
	| 'request.power'
	| 'request.sink'
	| 'request.sloops'
	| 'request.overclocking'
	| 'request.optimisation'
	| 'settings.numbers'
	| 'settings.graph'
	| 'settings.planner'
	| 'settings.plan-defaults'
	| 'settings.hotkeys'
	| 'settings.account'
	| 'versions.game'
	| 'versions.custom'
	| 'mods.overview'
	| 'mods.editor'
	| 'account.plans';
